---
- name: Install Nessus and configure system for more ephemeral ports
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Configure number of ephemeral ports
      ansible.builtin.include_role:
        name: more_ephemeral_ports
    # The AWS CLI is required for the cloud-init job that configures
    # and initializes Nessus.
    #
    # There is no system package for AWS CLI for Ubuntu Noble Numbat,
    # but we can install it via snap.
    - name: Install AWS CLI
      community.general.snap:
        classic: true
        name:
          - aws-cli
    - name: Install Nessus
      ansible.builtin.include_role:
        name: nessus
      vars:
        nessus_package_bucket: "{{ build_bucket }}"
        nessus_version: "10.8.3"
