---
- hosts: all
  name: Install Nessus
  become: yes
  become_method: sudo
  roles:
    - role: nessus
      vars:
        package_bucket: "{{ build_bucket }}"

- hosts: all
  name: Configure maximum number of ephemeral ports
  become: yes
  become_method: sudo
  roles:
    - more_ephemeral_ports
