---
# We are installing cisagov/ansible-role-vnc-server so that we get the
# vnc user.  This is being done to allow Kali instances to ssh to
# Nessus instances using that user and its associated ssh keys.  There
# is no intention to actually use the VNC server on this instance.
- name: Install VNC
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install VNC
      ansible.builtin.include_role:
        name: vnc_server
      vars:
        # The user information and ssh keys for the VNC user
        vnc_server_password: "{{ lookup('aws_ssm', '/vnc/password') }}"
        vnc_server_private_ssh_key: |-
          {{ lookup('aws_ssm', '/vnc/ssh/ed25519_private_key') }}
        vnc_server_public_ssh_key: |-
          {{ lookup('aws_ssm', '/vnc/ssh/ed25519_public_key') }}
        # Note that we use the same UID for the VNC and Samba guest
        # users on all instances.  This helps us avoid UID/GID
        # collisions with files written to the EFS share.
        vnc_server_user_uid: 2048
    - name: Ensure wheel group exists
      ansible.builtin.group:
        name: wheel
    - name: Give wheel group passwordless sudo access
      ansible.builtin.copy:
        content: |
          %wheel ALL=(ALL:ALL) NOPASSWD: ALL
        dest: /etc/sudoers.d/passwordless-sudo-for-wheel
        mode: 0444
    - name: Add VNC user to wheel group
      ansible.builtin.user:
        append: true
        groups:
          - wheel
        name: "{{ vnc_server_username }}"
  vars:
    # The username for the VNC user, specified separately so we can
    # reuse it in the ansible.builtin.user task.
    vnc_server_username: "{{ lookup('aws_ssm', '/vnc/username') }}"
